blank_issues_enabled: false
contact_links:
  - name: Patchwork Isles Discussions
    url: https://github.com/your-org/Patchwork-Isles/discussions
    about: Ask questions, share playtest stories, or brainstorm story arcs.
